-- Run this once in the Supabase SQL Editor for an existing installation.
-- It is safe to run repeatedly.

alter table public.discord_users
  add column if not exists can_create_tasks boolean not null default false;

alter table public.discord_users
  add column if not exists can_delete_tasks boolean not null default false;

alter table public.discord_users
  add column if not exists can_manage_users boolean not null default false;

alter table public.discord_users
  drop constraint if exists discord_users_status_check;

alter table public.discord_users
  add constraint discord_users_status_check
  check (status in ('pending', 'approved', 'rejected', 'blocked'));

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  field_number integer check (field_number between 1 and 999),
  assigned_player text check (char_length(assigned_player) <= 64),
  urgency text not null default 'medium' check (urgency in ('low', 'medium', 'high')),
  done boolean not null default false,
  created_by text references public.discord_users(discord_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_done_idx on public.tasks(done);
create index if not exists tasks_created_idx on public.tasks(created_at desc);

alter table public.tasks enable row level security;
revoke all on table public.tasks from anon, authenticated;
