-- Run this once in Supabase SQL Editor.
create table if not exists public.discord_users (
  discord_id text primary key check (discord_id ~ '^[0-9]{17,20}$'),
  username text not null,
  global_name text,
  avatar_hash text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'blocked')),
  is_admin boolean not null default false,
  can_create_tasks boolean not null default false,
  can_delete_tasks boolean not null default false,
  can_manage_users boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists discord_users_status_idx on public.discord_users(status);
create index if not exists discord_users_created_idx on public.discord_users(created_at);

-- Idempotent migration for installations created with an older schema.
alter table public.discord_users add column if not exists can_create_tasks boolean not null default false;
alter table public.discord_users add column if not exists can_delete_tasks boolean not null default false;
alter table public.discord_users add column if not exists can_manage_users boolean not null default false;
alter table public.discord_users drop constraint if exists discord_users_status_check;
alter table public.discord_users add constraint discord_users_status_check
  check (status in ('pending', 'approved', 'rejected', 'blocked'));

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  field_number integer check (field_number between 1 and 999),
  assigned_player text check (char_length(assigned_player) <= 64),
  urgency text not null default 'medium' check (urgency in ('low', 'medium', 'high')),
  done boolean not null default false,
  created_by text references public.discord_users(discord_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_done_idx on public.tasks(done);
create index if not exists tasks_created_idx on public.tasks(created_at desc);

alter table public.discord_users enable row level security;
alter table public.tasks enable row level security;
revoke all on table public.discord_users from anon, authenticated;
revoke all on table public.tasks from anon, authenticated;

-- The Express backend uses the Supabase server-side secret key, so browser clients
-- do not need direct table access.
