-- FS25 Companion: complete, repeatable Supabase setup
-- Run this entire file once in the Supabase SQL Editor.
-- Existing users and tasks are preserved.

begin;

-- ---------------------------------------------------------------------------
-- Discord website users and permissions
-- ---------------------------------------------------------------------------
create table if not exists public.discord_users (
  discord_id text primary key check (discord_id ~ '^[0-9]{17,20}$'),
  username text not null,
  global_name text,
  avatar_hash text,
  status text not null default 'pending',
  is_admin boolean not null default false,
  can_create_tasks boolean not null default false,
  can_delete_tasks boolean not null default false,
  can_manage_users boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.discord_users add column if not exists username text;
alter table public.discord_users add column if not exists global_name text;
alter table public.discord_users add column if not exists avatar_hash text;
alter table public.discord_users add column if not exists status text default 'pending';
alter table public.discord_users add column if not exists is_admin boolean not null default false;
alter table public.discord_users add column if not exists can_create_tasks boolean not null default false;
alter table public.discord_users add column if not exists can_delete_tasks boolean not null default false;
alter table public.discord_users add column if not exists can_manage_users boolean not null default false;
alter table public.discord_users add column if not exists created_at timestamptz not null default now();
alter table public.discord_users add column if not exists updated_at timestamptz not null default now();

update public.discord_users set username = 'unknown' where username is null or btrim(username) = '';
update public.discord_users set status = 'pending' where status is null or status not in ('pending', 'approved', 'rejected', 'blocked');

alter table public.discord_users alter column username set not null;
alter table public.discord_users alter column status set default 'pending';
alter table public.discord_users alter column status set not null;
alter table public.discord_users drop constraint if exists discord_users_status_check;
alter table public.discord_users add constraint discord_users_status_check
  check (status in ('pending', 'approved', 'rejected', 'blocked'));

create index if not exists discord_users_status_idx on public.discord_users(status);
create index if not exists discord_users_created_idx on public.discord_users(created_at);

-- ---------------------------------------------------------------------------
-- Shared task board
-- Canonical columns match the tasks table already present in this project.
-- ---------------------------------------------------------------------------
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  task_name text not null,
  player_name text not null default '',
  field_number integer,
  priority text not null default 'medium',
  is_completed boolean not null default false,
  created_by text references public.discord_users(discord_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks add column if not exists task_name text;
alter table public.tasks add column if not exists player_name text default '';
alter table public.tasks add column if not exists field_number integer;
alter table public.tasks add column if not exists priority text default 'medium';
alter table public.tasks add column if not exists is_completed boolean default false;
alter table public.tasks add column if not exists created_by text;
alter table public.tasks add column if not exists created_at timestamptz default now();
alter table public.tasks add column if not exists updated_at timestamptz default now();

-- Import values from the temporary column names used by an earlier build.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'name'
  ) then
    execute $sql$update public.tasks set task_name = coalesce(task_name, name) where task_name is null$sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'assigned_player'
  ) then
    execute $sql$update public.tasks set player_name = coalesce(nullif(player_name, ''), assigned_player, '')$sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'urgency'
  ) then
    execute $sql$update public.tasks set priority = coalesce(priority, urgency, 'medium')$sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'tasks' and column_name = 'done'
  ) then
    execute $sql$update public.tasks set is_completed = coalesce(is_completed, done, false)$sql$;
  end if;
end
$$;

update public.tasks set task_name = 'Neue Aufgabe' where task_name is null or btrim(task_name) = '';
update public.tasks set player_name = '' where player_name is null;
update public.tasks
set priority = case lower(coalesce(priority, 'medium'))
  when 'low' then 'low'
  when 'niedrig' then 'low'
  when 'high' then 'high'
  when 'hoch' then 'high'
  else 'medium'
end;
update public.tasks set is_completed = false where is_completed is null;
update public.tasks set created_at = now() where created_at is null;
update public.tasks set updated_at = coalesce(created_at, now()) where updated_at is null;

alter table public.tasks alter column task_name set not null;
alter table public.tasks alter column player_name set default '';
alter table public.tasks alter column player_name set not null;
alter table public.tasks alter column priority set default 'medium';
alter table public.tasks alter column priority set not null;
alter table public.tasks alter column is_completed set default false;
alter table public.tasks alter column is_completed set not null;
alter table public.tasks alter column created_at set default now();
alter table public.tasks alter column created_at set not null;
alter table public.tasks alter column updated_at set default now();
alter table public.tasks alter column updated_at set not null;

alter table public.tasks drop constraint if exists tasks_priority_check;
alter table public.tasks add constraint tasks_priority_check
  check (priority in ('low', 'medium', 'high'));

create index if not exists tasks_completed_idx on public.tasks(is_completed);
create index if not exists tasks_created_idx on public.tasks(created_at desc);

-- Browser clients do not access these tables directly. The Express backend
-- uses the Supabase server-side secret key and therefore bypasses RLS.
alter table public.discord_users enable row level security;
alter table public.tasks enable row level security;
revoke all on table public.discord_users from anon, authenticated;
revoke all on table public.tasks from anon, authenticated;

commit;

-- Make PostgREST immediately recognize the newly added columns.
notify pgrst, 'reload schema';
